"""all models added

Revision ID: 990a6e3ee135
Revises: 
Create Date: 2025-03-10 00:36:16.299476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '990a6e3ee135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_unit')
    op.drop_table('booking')
    op.drop_table('login')
    op.drop_table('charging_station')
    op.drop_table('request mechanic')
    op.drop_table('user')
    op.drop_table('feedback')
    op.drop_table('delivery agent')
    op.drop_table('mobilunitrequest')
    op.drop_table('assign')
    op.drop_table('slot')
    op.drop_table('location')
    op.drop_table('mechanic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fname', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('m_latitude', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('m_longitude', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('location',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('slot',
    sa.Column('slot_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('slot_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('details', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('slot_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('assign',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('m_unit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mobilunitrequest',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('m_unitid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=202), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('delivery agent',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('longitude', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fname', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('place', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pin', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('post', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('phone', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('request mechanic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('longitude', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('charging_station',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('place', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('phone', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('login',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('booking',
    sa.Column('bid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slotid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_time', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('booking_date', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('bid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mobile_unit',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('vehicle_num', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
